### ISSUE TITLE
Annotation on Custom dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [iver56/toy-object-detector#1]
How do I train it on my own dataset?How the dataset looks like?

**Comment by iver56** [comment]
You need:

* Images
* Bounding box annotations
* A list of classes

If you run `generate_dataset.py` of this repo, you will be able to go into the `data/training` folder and inspect the format of the dataset that keras-retinanet expects.

See also: https://github.com/fizyr/keras-retinanet

For more help, join the #keras-retinanet Keras Slack channel for discussions and questions
